-- ============================================================
-- Synapse — Database Schema Migration
-- ============================================================
-- Run this in Supabase SQL Editor (Dashboard → SQL Editor)
-- This creates all tables, RLS policies, and admin functions.
-- ============================================================


-- ──────────────────────────────────────────────────────────────
-- 0. EXTENSIONS & TYPES
-- ──────────────────────────────────────────────────────────────

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TYPE public.app_role AS ENUM ('admin', 'user');
CREATE TYPE public.subscription_status AS ENUM (
    'free', 'trial', 'active', 'cancelled', 'past_due', 'expired'
);


-- ──────────────────────────────────────────────────────────────
-- 1. USER ROLES (for admin JWT claim injection)
-- ──────────────────────────────────────────────────────────────

CREATE TABLE public.user_roles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    role       public.app_role NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, role)
);

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- No public access — only the auth hook can read this
REVOKE ALL ON TABLE public.user_roles FROM authenticated, anon, public;


-- ──────────────────────────────────────────────────────────────
-- 2. CUSTOM ACCESS TOKEN HOOK (injects role into JWT)
-- ──────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    claims     jsonb;
    user_role  public.app_role;
BEGIN
    -- Get the user's role
    SELECT role INTO user_role
    FROM public.user_roles
    WHERE user_id = (event->>'user_id')::uuid
    LIMIT 1;

    claims := event->'claims';

    IF user_role IS NOT NULL THEN
        claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
    ELSE
        claims := jsonb_set(claims, '{user_role}', '"user"');
    END IF;

    event := jsonb_set(event, '{claims}', claims);
    RETURN event;
END;
$$;

-- Grant the auth admin role access to run the hook
GRANT USAGE ON SCHEMA public TO supabase_auth_admin;
GRANT EXECUTE ON FUNCTION public.custom_access_token_hook TO supabase_auth_admin;
GRANT SELECT ON TABLE public.user_roles TO supabase_auth_admin;

-- NOTE: After running this, enable the hook in:
-- Dashboard → Authentication → Hooks → Custom Access Token → select this function


-- ──────────────────────────────────────────────────────────────
-- 3. PROFILES (extends auth.users)
-- ──────────────────────────────────────────────────────────────

CREATE TABLE public.profiles (
    id                    UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email                 TEXT NOT NULL DEFAULT '',
    display_name          TEXT DEFAULT '',
    avatar_url            TEXT DEFAULT '',
    subscription_status   public.subscription_status NOT NULL DEFAULT 'free',
    subscription_id       TEXT DEFAULT '',           -- Lemon Squeezy or Paymob subscription ID
    subscription_provider TEXT DEFAULT '',           -- 'lemonsqueezy' or 'paymob'
    trial_ends_at         TIMESTAMPTZ,
    subscription_ends_at  TIMESTAMPTZ,
    customer_portal_url   TEXT DEFAULT '',           -- Lemon Squeezy customer portal
    banned_at             TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;


-- ──────────────────────────────────────────────────────────────
-- 4. AGENTS (devices running synapse-agent)
-- ──────────────────────────────────────────────────────────────

CREATE TABLE public.agents (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name         TEXT NOT NULL DEFAULT 'My Machine',
    hostname     TEXT DEFAULT '',
    os           TEXT DEFAULT '',                     -- 'windows', 'darwin', 'linux'
    tools        JSONB NOT NULL DEFAULT '[]'::jsonb,  -- ["copilot", "claude", "gemini"]
    work_dir     TEXT DEFAULT '',
    is_online    BOOLEAN NOT NULL DEFAULT false,
    last_seen_at TIMESTAMPTZ DEFAULT now(),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.agents ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_agents_user_id ON public.agents(user_id);
CREATE INDEX idx_agents_online ON public.agents(is_online) WHERE is_online = true;


-- ──────────────────────────────────────────────────────────────
-- 5. CONVERSATIONS
-- ──────────────────────────────────────────────────────────────

CREATE TABLE public.conversations (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    agent_id   UUID REFERENCES public.agents(id) ON DELETE SET NULL,
    tool       TEXT NOT NULL DEFAULT 'copilot',
    title      TEXT DEFAULT 'New Conversation',
    work_dir   TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_conversations_user_id ON public.conversations(user_id);
CREATE INDEX idx_conversations_updated ON public.conversations(updated_at DESC);


-- ──────────────────────────────────────────────────────────────
-- 6. MESSAGES
-- ──────────────────────────────────────────────────────────────

CREATE TABLE public.messages (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
    role            TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content         TEXT NOT NULL DEFAULT '',
    metadata        JSONB DEFAULT '{}'::jsonb,    -- exit_code, duration, timed_out, tool
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_messages_conversation ON public.messages(conversation_id, created_at);


-- ──────────────────────────────────────────────────────────────
-- 7. PROMPT LOGS (lightweight usage tracking for admin analytics)
-- ──────────────────────────────────────────────────────────────

CREATE TABLE public.prompt_logs (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    agent_id    UUID REFERENCES public.agents(id) ON DELETE SET NULL,
    tool        TEXT NOT NULL DEFAULT 'copilot',
    duration_ms INT DEFAULT 0,
    exit_code   INT DEFAULT 0,
    status      TEXT DEFAULT 'success',              -- 'success', 'error', 'timeout', 'cancelled'
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.prompt_logs ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_prompt_logs_user ON public.prompt_logs(user_id);
CREATE INDEX idx_prompt_logs_created ON public.prompt_logs(created_at DESC);
CREATE INDEX idx_prompt_logs_tool ON public.prompt_logs(tool);


-- ──────────────────────────────────────────────────────────────
-- 8. PAYMENT EVENTS (audit log for webhooks)
-- ──────────────────────────────────────────────────────────────

CREATE TABLE public.payment_events (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    provider   TEXT NOT NULL DEFAULT '',               -- 'lemonsqueezy' or 'paymob'
    event_name TEXT NOT NULL DEFAULT '',               -- 'subscription_created', etc.
    payload    JSONB DEFAULT '{}'::jsonb,              -- Raw webhook payload
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.payment_events ENABLE ROW LEVEL SECURITY;

-- Payment events: admin only
CREATE POLICY "admin_only_payment_events"
ON public.payment_events FOR SELECT TO authenticated
USING ((SELECT (auth.jwt()->>'user_role')) = 'admin');


-- ──────────────────────────────────────────────────────────────
-- 9. AUTO-CREATE PROFILE ON SIGNUP (trigger)
-- ──────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    INSERT INTO public.profiles (id, email, display_name, avatar_url, subscription_status, trial_ends_at)
    VALUES (
        NEW.id,
        COALESCE(NEW.email, ''),
        COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', ''),
        COALESCE(NEW.raw_user_meta_data->>'avatar_url', ''),
        'trial',
        now() + interval '7 days'   -- 7-day free trial
    );

    -- Also create a default 'user' role
    INSERT INTO public.user_roles (user_id, role)
    VALUES (NEW.id, 'user');

    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ──────────────────────────────────────────────────────────────
-- 10. RLS POLICIES
-- ──────────────────────────────────────────────────────────────

-- Helper: check if current user is admin (cached per statement)
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
    SELECT COALESCE((SELECT auth.jwt()->>'user_role') = 'admin', false);
$$;

-- ── Profiles ──

CREATE POLICY "users_read_own_profile"
ON public.profiles FOR SELECT TO authenticated
USING (id = (SELECT auth.uid()) OR (SELECT public.is_admin()));

CREATE POLICY "users_update_own_profile"
ON public.profiles FOR UPDATE TO authenticated
USING (id = (SELECT auth.uid()))
WITH CHECK (id = (SELECT auth.uid()));

CREATE POLICY "admin_update_any_profile"
ON public.profiles FOR UPDATE TO authenticated
USING ((SELECT public.is_admin()))
WITH CHECK ((SELECT public.is_admin()));

-- ── Agents ──

CREATE POLICY "users_manage_own_agents"
ON public.agents FOR ALL TO authenticated
USING (user_id = (SELECT auth.uid()) OR (SELECT public.is_admin()));

-- ── Conversations ──

CREATE POLICY "users_manage_own_conversations"
ON public.conversations FOR ALL TO authenticated
USING (user_id = (SELECT auth.uid()) OR (SELECT public.is_admin()));

-- ── Messages (access via conversation ownership) ──

CREATE POLICY "users_read_own_messages"
ON public.messages FOR SELECT TO authenticated
USING (
    conversation_id IN (
        SELECT id FROM public.conversations WHERE user_id = (SELECT auth.uid())
    )
    OR (SELECT public.is_admin())
);

CREATE POLICY "users_insert_own_messages"
ON public.messages FOR INSERT TO authenticated
WITH CHECK (
    conversation_id IN (
        SELECT id FROM public.conversations WHERE user_id = (SELECT auth.uid())
    )
);

-- ── Prompt Logs ──

CREATE POLICY "admin_read_prompt_logs"
ON public.prompt_logs FOR SELECT TO authenticated
USING ((SELECT public.is_admin()));

CREATE POLICY "users_insert_prompt_logs"
ON public.prompt_logs FOR INSERT TO authenticated
WITH CHECK (user_id = (SELECT auth.uid()));


-- ──────────────────────────────────────────────────────────────
-- 11. REALTIME RLS (channel-level authorization)
-- ──────────────────────────────────────────────────────────────
-- These restrict Broadcast so users can only access their own channel.
-- Channel naming convention: "agent:{user_uuid}"
--
-- IMPORTANT: Also disable "Allow public access" in:
-- Dashboard → Project Settings → Realtime → uncheck "Allow public access"
-- ──────────────────────────────────────────────────────────────

CREATE POLICY "user_broadcast_select"
ON "realtime"."messages"
FOR SELECT TO authenticated
USING (
    realtime.topic() = 'agent:' || (SELECT auth.uid()::text)
    AND realtime.messages.extension = 'broadcast'
);

CREATE POLICY "user_broadcast_insert"
ON "realtime"."messages"
FOR INSERT TO authenticated
WITH CHECK (
    realtime.topic() = 'agent:' || (SELECT auth.uid()::text)
    AND realtime.messages.extension = 'broadcast'
);
